name: CI - Validacion Node.js API

on:
  push:
    branches:
      - Dev
      - Qa
      - PRD
      - Master
      - main
  pull_request:
    branches:
      - Dev
      - Qa
      - PRD
      - Master
      - main

jobs:
  build-test:
    name: Build, Lint, Test and Docker Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v6

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "npm"

      - name: Instalar dependencias
        run: npm ci

      - name: Analisis estatico
        run: npm run lint

      - name: Ejecutar pruebas
        run: npm test

      - name: Validar construccion Docker
        run: docker build -t colombia-departamentos-api:ci .